server:
  port: 5000

spring:
  thymeleaf:
    enabled: false
  datasource:
    url: jdbc:hsqldb:hsql://localhost/pilot
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: hsql
  jooq:
    sql-dialect: org.hibernate.dialect.HSQLDialect

joinfaces:
  jsf:
    PROJECT_STAGE: Development
  primefaces:
    theme: south-street
