server:
  port: 7000

spring:
  thymeleaf:
    enabled: false
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9010/pilot
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: hsql
  jooq:
    sql-dialect: org.hibernate.dialect.HSQLDialect

joinfaces:
  primefaces:
    theme: saga
  faces:
    project-stage: Development
