server:
  port: 7000

spring:
  thymeleaf:
    enabled: false
  datasource:
    url: jdbc:hsqldb:hsql://localhost/pilot
    username: sa
    password:
    hikari:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      transaction-isolation: 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: hsql

joinfaces:
  primefaces:
    theme: saga
  faces:
    project-stage: Development
  myfaces:
    resource-bundle-control: jsf
